/*
 * Created on Sep 21, 2007
 *
 * Copyright (c) 2007, The JUNG Authors
 *
 * All rights reserved.
 *
 * This software is open-source under the BSD license; see either
 * "license.txt" or
 * https://github.com/jrtom/jung/blob/master/LICENSE for a description.
 */
package edu.uci.ics.jung.io

import com.google.common.collect.BiMap
import com.google.common.collect.HashBiMap
import com.google.common.graph.MutableNetwork
import edu.uci.ics.jung.algorithms.util.MapSettableTransformer
import edu.uci.ics.jung.algorithms.util.SettableTransformer
import java.io.FileReader
import java.io.IOException
import java.io.Reader
import java.util.HashMap
import java.util.LinkedList
import java.util.function.Supplier
import javax.xml.parsers.ParserConfigurationException
import javax.xml.parsers.SAXParser
import javax.xml.parsers.SAXParserFactory
import org.xml.sax.Attributes
import org.xml.sax.InputSource
import org.xml.sax.SAXException
import org.xml.sax.SAXNotSupportedException
import org.xml.sax.helpers.DefaultHandler

/**
 * Reads in data from a GraphML-formatted file and generates graphs based on that data. Currently
 * supports the following parts of the GraphML specification:
 *
 * - graphs
 * - directed and undirected edges
 * - graph, node, edge `data`
 * - graph, node, edge descriptions and `data` descriptions
 * - node and edge IDs
 *
 * Each of these is exposed via appropriate `get` methods.
 *
 * Does not currently support nested graphs, hypergraphs, or ports.
 *
 * Note that the user is responsible for supplying a graph `Factory` that can support
 * the edge types in the supplied GraphML file. If the graph generated by the `Factory`
 * is not compatible (for example: if the graph does not accept directed edges, and the GraphML file
 * contains a directed edge) then the results are graph-implementation-dependent.
 *
 * @see [GraphML Specification](http://graphml.graphdrawing.org/specification.html)
 */
open class GraphMLReader<G : MutableNetwork<N, E>, N : Any, E : Any> : DefaultHandler {

  internal enum class TagState {
    NO_TAG,
    NODE,
    EDGE,
    HYPEREDGE,
    ENDPOINT,
    GRAPH,
    DATA,
    KEY,
    DESC,
    DEFAULT_KEY,
    GRAPHML,
    OTHER
  }

  internal enum class KeyType {
    NONE,
    NODE,
    EDGE,
    GRAPH,
    ALL
  }

  internal var saxp: SAXParser
  internal var default_directed: Boolean = false
  internal var current_graph: G? = null
  internal var current_node: N? = null
  internal var current_edge: E? = null
  internal var current_key: String? = null
  internal var current_states: LinkedList<TagState>
  internal var tag_state: BiMap<String, TagState>
  internal var graph_factory: Supplier<G>? = null
  internal var node_factory: Supplier<N>?
  internal var edge_factory: Supplier<E>?
  internal lateinit var node_ids: BiMap<N, String>
  internal lateinit var edge_ids: BiMap<E, String>
  internal lateinit var graph_metadata: MutableMap<String, GraphMLMetadata<G>>
  internal lateinit var node_metadata: MutableMap<String, GraphMLMetadata<N>>
  internal lateinit var edge_metadata: MutableMap<String, GraphMLMetadata<E>>
  internal lateinit var node_desc: MutableMap<N, String>
  internal lateinit var edge_desc: MutableMap<E, String>
  internal lateinit var graph_desc: MutableMap<G, String>
  internal var key_type: KeyType = KeyType.NONE

  internal var graphs: MutableList<G> = mutableListOf()

  internal var current_text: StringBuilder = StringBuilder()

  /**
   * Creates a `GraphMLReader` instance with the specified node and edge factories.
   *
   * @param node_factory the node supplier to use to create node objects
   * @param edge_factory the edge supplier to use to create edge objects
   * @throws ParserConfigurationException if a SAX parser cannot be constructed
   * @throws SAXException if the SAX parser factory cannot be constructed
   */
  @Throws(ParserConfigurationException::class, SAXException::class)
  constructor(node_factory: Supplier<N>?, edge_factory: Supplier<E>?) {
    current_node = null
    current_edge = null

    val saxParserFactory = SAXParserFactory.newInstance()
    saxp = saxParserFactory.newSAXParser()

    current_states = LinkedList<TagState>()

    tag_state = HashBiMap.create<String, TagState>()
    tag_state.put("node", TagState.NODE)
    tag_state.put("edge", TagState.EDGE)
    tag_state.put("endpoint", TagState.ENDPOINT)
    tag_state.put("graph", TagState.GRAPH)
    tag_state.put("data", TagState.DATA)
    tag_state.put("key", TagState.KEY)
    tag_state.put("desc", TagState.DESC)
    tag_state.put("default", TagState.DEFAULT_KEY)
    tag_state.put("graphml", TagState.GRAPHML)

    this.key_type = KeyType.NONE

    this.node_factory = node_factory
    this.edge_factory = edge_factory
  }

  /**
   * Creates a `GraphMLReader` instance that assigns the node and edge `id`
   * strings to be the node and edge objects, as well as their IDs. Note that this requires that (a)
   * each edge have a valid ID, which is not normally a requirement for edges in GraphML, and (b)
   * that the node and edge types be assignment-compatible with `String`.
   *
   * @throws ParserConfigurationException if a SAX parser cannot be constructed
   * @throws SAXException if the SAX parser factory cannot be constructed
   */
  @Throws(ParserConfigurationException::class, SAXException::class)
  constructor() : this(null, null)

  /**
   * Returns a list of the graphs parsed from the specified reader, as created by the specified
   * Supplier.
   *
   * @param reader the source of the graph data in GraphML format
   * @param graph_factory used to build graph instances
   * @return the graphs parsed from the specified reader
   * @throws IOException if an error is encountered while parsing the graph
   */
  @Throws(IOException::class)
  fun loadMultiple(reader: Reader, graph_factory: Supplier<G>): List<G> {
    this.graph_factory = graph_factory
    initializeData()
    clearData()
    parse(reader)

    return graphs
  }

  /**
   * Returns a list of the graphs parsed from the specified file, as created by the specified
   * Supplier.
   *
   * @param filename the source of the graph data in GraphML format
   * @param graph_factory used to build graph instances
   * @return the graphs parsed from the specified file
   * @throws IOException if an error is encountered while parsing the graph
   */
  @Throws(IOException::class)
  fun loadMultiple(filename: String, graph_factory: Supplier<G>): List<G> {
    return loadMultiple(FileReader(filename), graph_factory)
  }

  /**
   * Populates the specified graph with the data parsed from the reader.
   *
   * @param reader the source of the graph data in GraphML format
   * @param g the graph instance to populate
   * @throws IOException if an error is encountered while parsing the graph
   */
  @Throws(IOException::class)
  fun load(reader: Reader, g: G) {
    this.current_graph = g
    this.graph_factory = null
    initializeData()
    clearData()

    parse(reader)
  }

  /**
   * Populates the specified graph with the data parsed from the specified file.
   *
   * @param filename the source of the graph data in GraphML format
   * @param g the graph instance to populate
   * @throws IOException if an error is encountered while parsing the graph
   */
  @Throws(IOException::class)
  fun load(filename: String, g: G) {
    load(FileReader(filename), g)
  }

  internal open fun clearData() {
    this.node_ids.clear()
    this.node_desc.clear()

    this.edge_ids.clear()
    this.edge_desc.clear()

    this.graph_desc.clear()
  }

  /**
   * This is separate from initialize() because these data structures are shared among all graphs
   * loaded (i.e., they're defined inside `graphml` rather than `graph`).
   */
  internal open fun initializeData() {
    this.node_ids = HashBiMap.create<N, String>()
    this.node_desc = HashMap<N, String>()
    this.node_metadata = HashMap<String, GraphMLMetadata<N>>()

    this.edge_ids = HashBiMap.create<E, String>()
    this.edge_desc = HashMap<E, String>()
    this.edge_metadata = HashMap<String, GraphMLMetadata<E>>()

    this.graph_desc = HashMap<G, String>()
    this.graph_metadata = HashMap<String, GraphMLMetadata<G>>()
  }

  @Throws(IOException::class)
  internal open fun parse(reader: Reader) {
    try {
      saxp.parse(InputSource(reader), this)
      reader.close()
    } catch (saxe: SAXException) {
      throw IOException(saxe.message)
    }
  }

  @Throws(SAXNotSupportedException::class)
  override fun startElement(uri: String, name: String, qName: String, atts: Attributes) {
    val tag = qName.lowercase()
    var state = tag_state[tag]
    if (state == null) {
      state = TagState.OTHER
    }

    when (state) {
      TagState.GRAPHML -> {}

      TagState.NODE -> {
        if (this.current_graph == null) {
          throw SAXNotSupportedException("Graph must be defined prior to elements")
        }
        if (this.current_edge != null || this.current_node != null) {
          throw SAXNotSupportedException("Nesting elements not supported")
        }

        createNode(atts)
      }

      TagState.ENDPOINT -> {
        if (this.current_graph == null) {
          throw SAXNotSupportedException("Graph must be defined prior to elements")
        }
        if (this.current_edge == null) {
          throw SAXNotSupportedException("No edge defined for endpoint")
        }
        val endpoint_atts = getAttributeMap(atts)
        val node = endpoint_atts.remove("node")
          ?: throw SAXNotSupportedException("Endpoint must include an 'id' attribute")
        val v = node_ids.inverse()[node]
          ?: throw SAXNotSupportedException("Endpoint refers to nonexistent node ID: $node")

        this.current_node = v
      }

      TagState.EDGE -> {
        if (this.current_graph == null) {
          throw SAXNotSupportedException("Graph must be defined prior to elements")
        }
        if (this.current_edge != null || this.current_node != null) {
          throw SAXNotSupportedException("Nesting elements not supported")
        }

        createEdge(atts, state)
      }

      TagState.HYPEREDGE -> throw SAXNotSupportedException("Hyperedges not supported")

      TagState.GRAPH -> {
        if (this.current_graph != null && graph_factory != null) {
          throw SAXNotSupportedException("Nesting graphs not currently supported")
        }

        // graph Supplier is null if there's only one graph
        if (graph_factory != null) {
          current_graph = graph_factory!!.get()
        }

        // reset all non-key data structures (to avoid collisions between different graphs)
        clearData()

        // set up default direction of edges
        val graph_atts = getAttributeMap(atts)
        val default_direction = graph_atts.remove("edgedefault")
          ?: throw SAXNotSupportedException("All graphs must specify a default edge direction")
        when (default_direction) {
          "directed" -> this.default_directed = true
          "undirected" -> this.default_directed = false
          else -> throw SAXNotSupportedException(
            "Invalid or unrecognized default edge direction: $default_direction"
          )
        }

        // put remaining attribute/value pairs in graph_data
        addExtraData(graph_atts, graph_metadata, current_graph!!)
      }

      TagState.DATA -> {
        if (this.current_states.contains(TagState.DATA)) {
          throw SAXNotSupportedException("Nested data not supported")
        }
        handleData(atts)
      }

      TagState.KEY -> createKey(atts)

      else -> {}
    }

    current_states.addFirst(state)
  }

  private fun <T : Any> addExtraData(
    atts: MutableMap<String, String>,
    metadata_map: MutableMap<String, GraphMLMetadata<T>>,
    current_elt: T
  ) {
    // load in the default values; these override anything that might
    // be in the attribute map (because that's not really a proper
    // way to associate data)
    for ((_, gmlm) in metadata_map) {
      if (gmlm.default_value != null) {
        @Suppress("UNCHECKED_CAST")
        val st = gmlm.transformer as SettableTransformer<T, String>
        st.set(current_elt as T, gmlm.default_value!!)
      }
    }

    // place remaining items in data
    for ((key, value) in atts) {
      var key_data = metadata_map[key]
      val st: SettableTransformer<T, String>
      if (key_data != null) {
        // if there's a default value, don't override it
        if (key_data.default_value != null) {
          continue
        }
        @Suppress("UNCHECKED_CAST")
        st = key_data.transformer as SettableTransformer<T, String>
      } else {
        st = MapSettableTransformer<T, String>(HashMap())
        @Suppress("UNCHECKED_CAST")
        key_data = GraphMLMetadata<T>(null, null, st as java.util.function.Function<T, String>)
        metadata_map[key] = key_data
      }
      st.set(current_elt as T, value)
    }
  }

  @Throws(SAXNotSupportedException::class)
  override fun characters(ch: CharArray, start: Int, length: Int) {
    this.current_text.append(String(ch, start, length))
  }

  @Throws(SAXNotSupportedException::class)
  internal open fun <T : Any> addDatum(
    metadata: MutableMap<String, GraphMLMetadata<T>>,
    current_elt: T,
    text: String
  ) {
    if (metadata.containsKey(this.current_key)) {
      @Suppress("UNCHECKED_CAST")
      val st = metadata[this.current_key]!!.transformer as SettableTransformer<T, String>
      st.set(current_elt as T, text)
    } else {
      throw SAXNotSupportedException(
        "key ${this.current_key} not valid for element $current_elt"
      )
    }
  }

  @Throws(SAXNotSupportedException::class)
  override fun endElement(uri: String, name: String, qName: String) {
    val text = current_text.toString().trim()
    current_text.setLength(0)

    val tag = qName.lowercase()
    var state = tag_state[tag]
    if (state == null) {
      state = TagState.OTHER
    }
    if (state == TagState.OTHER) {
      return
    }

    if (state != current_states.first) {
      throw SAXNotSupportedException(
        "Unbalanced tags: opened ${tag_state.inverse()[current_states.first]}, closed $tag"
      )
    }

    when (state) {
      TagState.NODE, TagState.ENDPOINT -> current_node = null

      TagState.EDGE -> current_edge = null

      TagState.HYPEREDGE -> throw SAXNotSupportedException("Hypergraphs not currently supported")

      TagState.GRAPH -> current_graph = null

      TagState.KEY -> current_key = null

      TagState.DESC -> {
        when (this.current_states[1]) { // go back one
          TagState.GRAPH -> graph_desc[current_graph!!] = text
          TagState.NODE, TagState.ENDPOINT -> node_desc[current_node!!] = text
          TagState.EDGE, TagState.HYPEREDGE -> edge_desc[current_edge!!] = text
          TagState.DATA -> {
            when (key_type) {
              KeyType.GRAPH -> graph_metadata[current_key]!!.description = text
              KeyType.NODE -> node_metadata[current_key]!!.description = text
              KeyType.EDGE -> edge_metadata[current_key]!!.description = text
              KeyType.ALL -> {
                graph_metadata[current_key]!!.description = text
                node_metadata[current_key]!!.description = text
                edge_metadata[current_key]!!.description = text
              }
              else -> throw SAXNotSupportedException(
                "Invalid key type specified for default: $key_type"
              )
            }
          }
          else -> {}
        }
      }

      TagState.DATA -> {
        this.key_type = KeyType.NONE
        when (this.current_states[1]) {
          TagState.GRAPH -> addDatum(graph_metadata, current_graph!!, text)
          TagState.NODE, TagState.ENDPOINT -> addDatum(node_metadata, current_node!!, text)
          TagState.EDGE, TagState.HYPEREDGE -> addDatum(edge_metadata, current_edge!!, text)
          else -> {}
        }
      }

      TagState.DEFAULT_KEY -> {
        if (this.current_states[1] != TagState.KEY) {
          throw SAXNotSupportedException(
            "'default' only defined in context of 'key' tag: stack: $current_states"
          )
        }

        when (key_type) {
          KeyType.GRAPH -> graph_metadata[current_key]!!.default_value = text
          KeyType.NODE -> node_metadata[current_key]!!.default_value = text
          KeyType.EDGE -> edge_metadata[current_key]!!.default_value = text
          KeyType.ALL -> {
            graph_metadata[current_key]!!.default_value = text
            node_metadata[current_key]!!.default_value = text
            edge_metadata[current_key]!!.default_value = text
          }
          else -> throw SAXNotSupportedException(
            "Invalid key type specified for default: $key_type"
          )
        }
      }

      else -> {}
    }

    current_states.removeFirst()
  }

  internal open fun getAttributeMap(atts: Attributes): MutableMap<String, String> {
    val att_map = HashMap<String, String>()
    for (i in 0 until atts.length) {
      att_map[atts.getQName(i)] = atts.getValue(i)
    }
    return att_map
  }

  @Throws(SAXNotSupportedException::class)
  internal open fun handleData(atts: Attributes) {
    when (this.current_states.first) {
      TagState.GRAPH, TagState.NODE, TagState.ENDPOINT, TagState.EDGE, TagState.HYPEREDGE -> {}
      else -> throw SAXNotSupportedException(
        "'data' tag only defined if immediately containing tag is 'graph', 'node', 'edge', or 'hyperedge'"
      )
    }
    this.current_key = getAttributeMap(atts)["key"]
    if (this.current_key == null) {
      throw SAXNotSupportedException("'data' tag requires a key specification")
    }
    if (this.current_key == "") {
      throw SAXNotSupportedException("'data' tag requires a non-empty key")
    }
    if (!getGraphMetadata().containsKey(this.current_key)
      && !getNodeMetadata().containsKey(this.current_key)
      && !getEdgeMetadata().containsKey(this.current_key)
    ) {
      throw SAXNotSupportedException(
        "'data' tag's key specification must reference a defined key"
      )
    }
  }

  @Throws(SAXNotSupportedException::class)
  internal open fun createKey(atts: Attributes) {
    val key_atts = getAttributeMap(atts)
    val id = key_atts.remove("id")
    val for_type = key_atts.remove("for")

    if (for_type == null || for_type == "" || for_type == "all") {
      node_metadata[id!!] = GraphMLMetadata<N>(
        null, null, MapSettableTransformer<N, String>(HashMap())
      )
      edge_metadata[id] = GraphMLMetadata<E>(
        null, null, MapSettableTransformer<E, String>(HashMap())
      )
      graph_metadata[id] = GraphMLMetadata<G>(
        null, null, MapSettableTransformer<G, String>(HashMap())
      )
      key_type = KeyType.ALL
    } else {
      val type = tag_state[for_type]
      when (type) {
        TagState.NODE -> {
          node_metadata[id!!] = GraphMLMetadata<N>(
            null, null, MapSettableTransformer<N, String>(HashMap())
          )
          key_type = KeyType.NODE
        }
        TagState.EDGE, TagState.HYPEREDGE -> {
          edge_metadata[id!!] = GraphMLMetadata<E>(
            null, null, MapSettableTransformer<E, String>(HashMap())
          )
          key_type = KeyType.EDGE
        }
        TagState.GRAPH -> {
          graph_metadata[id!!] = GraphMLMetadata<G>(
            null, null, MapSettableTransformer<G, String>(HashMap())
          )
          key_type = KeyType.GRAPH
        }
        else -> throw SAXNotSupportedException("Invalid metadata target type: $for_type")
      }
    }

    this.current_key = id
  }

  @Suppress("UNCHECKED_CAST")
  @Throws(SAXNotSupportedException::class)
  internal open fun createNode(atts: Attributes) {
    val node_atts = getAttributeMap(atts)
    val id = node_atts.remove("id")
      ?: throw SAXNotSupportedException(
        "node attribute list missing 'id': $atts"
      )
    var v = node_ids.inverse()[id]

    if (v == null) {
      v = if (node_factory != null) {
        node_factory!!.get()
      } else {
        id as N
      }
      node_ids.put(v, id)
      this.current_graph!!.addNode(v)

      // put remaining attribute/value pairs in node_data
      addExtraData(node_atts, node_metadata, v)
    } else {
      throw SAXNotSupportedException(
        "Node id \"$id is a duplicate of an existing node ID"
      )
    }

    this.current_node = v
  }

  @Suppress("UNCHECKED_CAST")
  @Throws(SAXNotSupportedException::class)
  internal open fun createEdge(atts: Attributes, state: TagState) {
    val edge_atts = getAttributeMap(atts)

    val id = edge_atts.remove("id")
    val e: E
    if (edge_factory != null) {
      e = edge_factory!!.get()
    } else if (id != null) {
      e = id as E
    } else {
      throw IllegalArgumentException(
        "If no edge Supplier is supplied, edge id may not be null: $edge_atts"
      )
    }

    if (id != null) {
      if (edge_ids.containsKey(e)) {
        throw SAXNotSupportedException(
          "Edge id \"$id\" is a duplicate of an existing edge ID"
        )
      }
      edge_ids.put(e, id)
    }

    if (state == TagState.EDGE) {
      assignEdgeSourceTarget(e, atts, edge_atts)
    }

    // put remaining attribute/value pairs in edge_data
    addExtraData(edge_atts, edge_metadata, e)

    this.current_edge = e
  }

  @Throws(SAXNotSupportedException::class)
  internal open fun assignEdgeSourceTarget(
    e: E,
    atts: Attributes,
    edge_atts: MutableMap<String, String>
  ) {
    val source_id = edge_atts.remove("source")
      ?: throw SAXNotSupportedException(
        "edge attribute list missing 'source': $atts"
      )
    val source = node_ids.inverse()[source_id]
      ?: throw SAXNotSupportedException(
        "specified 'source' attribute \"$source_id\" does not match any node ID"
      )

    val target_id = edge_atts.remove("target")
      ?: throw SAXNotSupportedException(
        "edge attribute list missing 'target': $atts"
      )
    val target = node_ids.inverse()[target_id]
      ?: throw SAXNotSupportedException(
        "specified 'target' attribute \"$target_id\" does not match any node ID"
      )

    val directed = edge_atts.remove("directed")
    if (directed != null) {
      val isDirected = directed == "true"
      val isUndirected = directed == "false"
      if (!isDirected && !isUndirected) {
        throw SAXNotSupportedException(
          "Unrecognized edge direction specifier 'direction=\"$directed\"': " +
            "source: $source_id, target: $target_id"
        )
      }
      if (isDirected != default_directed) {
        throw SAXNotSupportedException(
          String.format(
            "Parser does not support graphs with directed and " +
              "undirected edges; default direction: %b, edge direction: %b: ",
            default_directed, if (isDirected) isDirected else isUndirected
          )
        )
      }
    }
    current_graph!!.addEdge(source, target, e)
  }

  /**
   * @return a bidirectional map relating nodes and IDs.
   */
  fun getNodeIDs(): BiMap<N, String> = node_ids

  /**
   * Returns a bidirectional map relating edges and IDs. This is not guaranteed to always be
   * populated (edge IDs are not required in GraphML files).
   *
   * @return a bidirectional map relating edges and IDs.
   */
  fun getEdgeIDs(): BiMap<E, String> = edge_ids

  /**
   * @return a map from graph type name to type metadata
   */
  fun getGraphMetadata(): Map<String, GraphMLMetadata<G>> = graph_metadata

  /**
   * @return a map from node type name to type metadata
   */
  fun getNodeMetadata(): Map<String, GraphMLMetadata<N>> = node_metadata

  /**
   * @return a map from edge type name to type metadata
   */
  fun getEdgeMetadata(): Map<String, GraphMLMetadata<E>> = edge_metadata

  /**
   * @return a map from graphs to graph descriptions
   */
  fun getGraphDescriptions(): Map<G, String> = graph_desc

  /**
   * @return a map from nodes to node descriptions
   */
  fun getNodeDescriptions(): Map<N, String> = node_desc

  /**
   * @return a map from edges to edge descriptions
   */
  fun getEdgeDescriptions(): Map<E, String> = edge_desc
}
