/*
 * Copyright (c) 2008, The JUNG Authors
 *
 * All rights reserved.
 *
 * This software is open-source under the BSD license; see either
 * "license.txt" or
 * https://github.com/jrtom/jung/blob/master/LICENSE for a description.
 */
package edu.uci.ics.jung.io.graphml

import com.google.common.base.Preconditions
import com.google.common.graph.MutableNetwork
import edu.uci.ics.jung.io.GraphIOException
import edu.uci.ics.jung.io.GraphReader
import edu.uci.ics.jung.io.graphml.parser.ElementParserRegistry
import edu.uci.ics.jung.io.graphml.parser.GraphMLEventFilter
import java.io.IOException
import java.io.InputStream
import java.io.Reader
import java.util.function.Function
import javax.xml.stream.XMLEventReader
import javax.xml.stream.XMLInputFactory
import javax.xml.stream.XMLStreamException
import javax.xml.stream.events.StartElement

/**
 * Reads in data from a GraphML-formatted file and generates graphs based on that data. Does not
 * currently support nested graphs.
 *
 * Note that the user is responsible for supplying a graph `Transformer` that will
 * create graphs capable of supporting the edge types in the supplied GraphML file. If the graph
 * generated by the `Factory` is not compatible (for example: if the graph does not
 * accept directed edges, and the GraphML file contains a directed edge) then the results are
 * graph-implementation-dependent.
 *
 * @author Nathan Mittler - nathan.mittler@gmail.com
 * @param G The graph type to be read from the GraphML file
 * @param N the node type The node type used by the graph
 * @param E the edge type The edge type used by the graph
 * @see [GraphML Specification](http://graphml.graphdrawing.org/specification.html)
 */
// TODO: do we actually need the G type, or can we just have it be "Network"?
// TODO: provide Graph/ValueGraph support?
// TODO: don't bother taking in a graph factory
open class GraphMLReader2<G : MutableNetwork<N, E>, N, E> : GraphReader<G, N, E> {

  protected var xmlEventReader: XMLEventReader? = null
  protected var fileReader: Reader?
  protected var graphTransformer: Function<GraphMetadata, G>?
  protected var nodeTransformer: Function<NodeMetadata, N>?
  protected var edgeTransformer: Function<EdgeMetadata, E>?
  protected var initialized: Boolean = false
  protected val document: GraphMLDocument = GraphMLDocument()
  protected val parserRegistry: ElementParserRegistry<G, N, E>
  private var inputStream: InputStream?

  /**
   * Constructs a GraphML reader around the given reader. This constructor requires the user to
   * supply transformation functions to convert from the GraphML metadata to Graph, Node, Edge
   * instances. These Function functions can be used as purely factories (i.e. the metadata is
   * disregarded) or can use the metadata to set particular fields in the objects.
   *
   * @param fileReader the reader for the input GraphML document.
   * @param graphTransformer Transformation function to convert from GraphML GraphMetadata to graph
   *     objects. This must be non-null.
   * @param nodeTransformer Transformation function to convert from GraphML NodeMetadata to node
   *     objects. This must be non-null.
   * @param edgeTransformer Transformation function to convert from GraphML EdgeMetadata to edge
   *     objects. This must be non-null.
   * @throws IllegalArgumentException thrown if any of the arguments are null.
   */
  constructor(
    fileReader: Reader,
    graphTransformer: Function<GraphMetadata, G>,
    nodeTransformer: Function<NodeMetadata, N>,
    edgeTransformer: Function<EdgeMetadata, E>
  ) {
    this.fileReader = Preconditions.checkNotNull(fileReader)
    this.graphTransformer = Preconditions.checkNotNull(graphTransformer)
    this.nodeTransformer = Preconditions.checkNotNull(nodeTransformer)
    this.edgeTransformer = Preconditions.checkNotNull(edgeTransformer)
    this.inputStream = null

    // Create the parser registry.
    this.parserRegistry = ElementParserRegistry(
      document.keyMap, graphTransformer, nodeTransformer, edgeTransformer
    )
  }

  /**
   * Constructs a GraphML reader around the given input stream. This constructor requires the user
   * to supply transformation functions to convert from the GraphML metadata to Graph, Node, Edge
   * instances. These Function functions can be used as purely factories (i.e. the metadata is
   * disregarded) or can use the metadata to set particular fields in the objects.
   *
   * @param inputStream the inputstream for the input GraphML document.
   * @param graphTransformer Transformation function to convert from GraphML GraphMetadata to graph
   *     objects. This must be non-null.
   * @param nodeTransformer Transformation function to convert from GraphML NodeMetadata to node
   *     objects. This must be non-null.
   * @param edgeTransformer Transformation function to convert from GraphML EdgeMetadata to edge
   *     objects. This must be non-null.
   * @throws IllegalArgumentException thrown if any of the arguments are null.
   */
  constructor(
    inputStream: InputStream,
    graphTransformer: Function<GraphMetadata, G>,
    nodeTransformer: Function<NodeMetadata, N>,
    edgeTransformer: Function<EdgeMetadata, E>
  ) {
    this.inputStream = Preconditions.checkNotNull(inputStream)
    this.graphTransformer = Preconditions.checkNotNull(graphTransformer)
    this.nodeTransformer = Preconditions.checkNotNull(nodeTransformer)
    this.edgeTransformer = Preconditions.checkNotNull(edgeTransformer)
    this.fileReader = null

    // Create the parser registry.
    this.parserRegistry = ElementParserRegistry(
      document.keyMap, graphTransformer, nodeTransformer, edgeTransformer
    )
  }

  // graphTransformer, nodeTransformer, edgeTransformer are accessible via their property getters

  /**
   * Verifies the object state and initializes this reader. All Function properties must be set and
   * be non-null or a `GraphReaderException` will be thrown. This method may be called more than
   * once. Successive calls will have no effect.
   *
   * @throws edu.uci.ics.jung.io.GraphIOException thrown if an error occurred.
   */
  @Throws(GraphIOException::class)
  fun init() {
    try {
      if (!initialized) {
        // Create the event reader.
        val factory = XMLInputFactory.newInstance()
        xmlEventReader = if (fileReader == null && inputStream != null) {
          factory.createXMLEventReader(inputStream)
        } else {
          factory.createXMLEventReader(fileReader)
        }
        xmlEventReader = factory.createFilteredReader(xmlEventReader, GraphMLEventFilter())

        initialized = true
      }
    } catch (e: Exception) {
      ExceptionConverter.convert(e)
    }
  }

  /**
   * Closes the GraphML reader and disposes of any resources.
   *
   * @throws edu.uci.ics.jung.io.GraphIOException thrown if an error occurs.
   */
  @Throws(GraphIOException::class)
  override fun close() {
    try {
      // Clear the contents of the document.
      document.clear()

      xmlEventReader?.close()
      fileReader?.close()
      inputStream?.close()
    } catch (e: IOException) {
      throw GraphIOException(e)
    } catch (e: XMLStreamException) {
      throw GraphIOException(e)
    } finally {
      fileReader = null
      inputStream = null
      xmlEventReader = null
      graphTransformer = null
      nodeTransformer = null
      edgeTransformer = null
    }
  }

  /**
   * Returns the object that contains the metadata read in from the GraphML document
   *
   * @return the GraphML document
   */
  fun getGraphMLDocument(): GraphMLDocument = document

  /**
   * Reads a single graph object from the GraphML document. Automatically calls `init` to
   * initialize the state of the reader.
   *
   * @return the graph that was read if one was found, otherwise null.
   */
  @Suppress("UNCHECKED_CAST")
  @Throws(GraphIOException::class)
  override fun readGraph(): G {
    try {
      // Initialize if not already.
      init()

      while (xmlEventReader!!.hasNext()) {
        val event = xmlEventReader!!.nextEvent()
        if (event.isStartElement) {
          val element = event as StartElement
          val name = element.name.localPart

          // The element should be one of: key, graph, graphml
          if (GraphMLConstants.KEY_NAME == name) {
            // Parse the key object.
            val key = parserRegistry.getParser(name).parse(xmlEventReader!!, element) as Key

            // Add the key to the key map.
            document.keyMap.addKey(key)
          } else if (GraphMLConstants.GRAPH_NAME == name) {
            // Parse the graph.
            val graph =
              parserRegistry.getParser(name).parse(xmlEventReader!!, element) as GraphMetadata

            // Add it to the graph metadata list.
            document.graphMetadata.add(graph)

            // Return the graph object.
            return graph.graph as G
          } else if (GraphMLConstants.GRAPHML_NAME == name) {
            // Ignore the graphML object.
          } else {
            // Encountered an unknown element - just skip by it.
            parserRegistry.unknownElementParser.parse(xmlEventReader!!, element)
          }
        } else if (event.isEndDocument) {
          break
        }
      }
    } catch (e: Exception) {
      ExceptionConverter.convert(e)
    }

    // We didn't read anything from the document.
    throw GraphIOException("Unable to read Graph from document - the document could be empty")
  }
}
